In [1]:
from sklearn.preprocessing import FunctionTransformer

In [2]:
import pandas as pd
import numpy as np
from get_path import get_path as gp

In [3]:
df = pd.read_csv(gp()).iloc[:, :5].dropna()

In [4]:
df.head()

    mean radius  mean texture  mean perimeter  mean area  mean smoothness
2         19.69         21.25          130.00     1203.0          0.10960
3         11.42         20.38           77.58      386.1          0.14250
8         13.00         21.82           87.50      519.8          0.12730
13        15.85         23.95          103.70      782.7          0.08401
14        13.73         22.61           93.60      578.3          0.11310

In [6]:
transformer = FunctionTransformer(
    np.log
)

In [7]:
transformer.fit_transform(df)

     mean radius  mean texture  mean perimeter  mean area  mean smoothness
2       2.980111      3.056357        4.867534   7.092574        -2.210918
3       2.435366      3.014554        4.351310   5.956096        -1.948413
8       2.564949      3.082827        4.471639   6.253444        -2.061209
13      2.763170      3.175968        4.641502   6.662749        -2.476819
14      2.619583      3.118392        4.539030   6.360093        -2.179483
..           ...           ...             ...        ...              ...
549     2.381396      3.186766        4.232511   5.890539        -2.502012
550     2.385086      3.067122        4.226980   5.887492        -2.599510
560     2.642622      3.301377        4.515027   6.397596        -2.309710
564     3.070840      3.108614        4.955827   7.299121        -2.198225
567     3.025291      3.378611        4.942356   7.142827        -2.138767

[176 rows x 5 columns]

# **If we want a 2D array as output**

In [11]:
transformer = FunctionTransformer(
    np.log,
    validate=True
)

In [12]:
transformer.fit_transform(df)

array([[ 2.98011089,  3.0563569 ,  4.86753445,  7.09257372, -2.2109179 ],
       [ 2.4353662 ,  3.01455403,  4.35130966,  5.9560964 , -1.94841328],
       [ 2.56494936,  3.08282698,  4.47163879,  6.25344412, -2.06120877],
       [ 2.7631695 ,  3.17596832,  4.64150212,  6.66274948, -2.47681944],
       [ 2.61958322,  3.11839229,  4.53903038,  6.36009277, -2.1794829 ],
       [ 2.98618686,  3.0978375 ,  4.86753445,  7.138867  , -2.31962953],
       [ 2.57108435,  2.75429745,  4.45003569,  6.25382881, -2.23026443],
       [ 2.25171276,  2.52091709,  4.09999523,  5.61276308, -2.27886857],
       [ 2.84141491,  2.79728133,  4.75359019,  6.81640724, -2.13199879],
       [ 2.67965073,  3.06944731,  4.57892887,  6.46894019, -2.24999264],
       [ 2.83438912,  3.17722015,  4.72561634,  6.80161668, -2.12276667],
       [ 2.95854948,  3.27601202,  4.85124871,  7.05789794, -2.36435412],
       [ 2.56725439,  2.91343703,  4.41413074,  6.26110993, -2.40983628],
       [ 2.60120711,  3.03591406,  4.48187197,  6.32650719, -2.28671174],
       [ 2.94811642,  3.2112468 ,  4.85437127,  7.00669523, -2.39898587],
       [ 2.58625914,  3.00963518,  4.46957953,  6.3011527 , -2.2624033 ],
       [ 2.92584615,  2.8678989 ,  4.81785928,  6.98100574, -2.20818442],
       [ 2.47989411,  2.90361698,  4.32691025,  6.08130525, -2.49362454],
       [ 2.90251989,  2.92852352,  4.78998862,  6.94022247, -2.1645638 ],
       [ 2.56878813,  2.9606231 ,  4.41413074,  6.26757998, -2.51825663],
       [ 2.15385304,  2.46725171,  3.9952606 ,  5.41387571, -2.32769779],
       [ 2.21626439,  2.62900699,  4.08092154,  5.56413719, -2.5612263 ],
       [ 2.54002595,  3.17136484,  4.41509868,  6.2126061 , -2.18747229],
       [ 2.20044162,  2.8524391 ,  4.07397177,  5.52345892, -2.23867177],
       [ 2.18470205,  2.68375751,  4.07397177,  5.49716823, -2.324524  ],
       [ 2.62466859,  2.75937683,  4.50457607,  6.3700722 , -2.29560948],
       [ 2.60490944,  2.3924258 ,  4.47631356,  6.32650719, -2.04716798],
       [ 3.00469201,  3.17680305,  4.96772779,  7.12689081, -2.05104847],
       [ 2.29010757,  2.96527307,  4.15810153,  5.69809969, -2.29759755],
       [ 2.5733753 ,  2.74470352,  4.468319  ,  6.27325429, -1.96754245],
       [ 2.65745841,  2.97807734,  4.58323128,  6.44556108, -2.54631408],
       [ 2.35232718,  3.00518743,  4.22887546,  5.81173962, -2.18747229],
       [ 2.9263822 ,  2.84024737,  4.79909088,  6.98193468, -2.24999264],
       [ 2.94443898,  2.93969088,  4.81543111,  7.03702761, -2.49896501],
       [ 2.71469474,  2.79667139,  4.60096134,  6.51397168, -2.16282315],
       [ 2.98517676,  3.22366434,  4.87060665,  7.08338785, -2.28769648],
       [ 2.91506437,  3.08694315,  4.78915702,  6.98007594, -2.36127409],
       [ 2.54709867,  3.11218109,  4.40329877,  6.22712938, -2.40185309],
       [ 2.42303125,  2.59450816,  4.29045944,  5.95272372, -2.15072274],
       [ 2.43624148,  2.85128437,  4.29945991,  5.98645201, -2.21457422],
       [ 2.46809953,  2.80819715,  4.36932126,  6.06842559, -2.21549039],
       [ 2.56494936,  3.03399099,  4.42496639,  6.2526743 , -2.17595244],
       [ 2.10644855,  3.0301337 ,  3.97537332,  5.31762968, -2.36392872],
       [ 2.48989419,  2.54474665,  4.34172534,  6.10613162, -2.37397369],
       [ 2.95438931,  2.76883167,  4.83866003,  7.05358573, -2.44253705],
       [ 3.14716498,  3.09285898,  5.0245382 ,  7.43011414, -2.47230637],
       [ 2.37954613,  2.27315628,  4.2307676 ,  5.87941504, -2.34403228],
       [ 2.86048512,  3.2059932 ,  4.75445189,  6.89223547, -2.25474776],
       [ 2.7060482 ,  2.83026783,  4.56663724,  6.53073184, -2.31719125],
       [ 2.51122396,  2.5168897 ,  4.36754731,  6.14010005, -2.27496993],
       [ 2.8009332 ,  3.0012172 ,  4.6940964 ,  6.72491359, -2.31962953],
       [ 2.43449016,  2.70270259,  4.29769349,  5.99645209, -2.40141145],
       [ 2.31055326,  2.71535678,  4.15512603,  5.76047782, -2.37871048],
       [ 2.46894663,  2.85589533,  4.32108165,  6.06122379, -2.29560948],
       [ 2.95386807,  3.11307077,  4.84811636,  7.04577658, -2.46240179],
       [ 2.67069441,  3.00667221,  4.54849401,  6.46567805, -2.31546772],
       [ 2.71601837,  2.8142104 ,  4.59289516,  6.5745178 , -2.42181918],
       [ 2.5733753 ,  3.11529151,  4.46613798,  6.27174429, -2.30058709],
       [ 3.02431973,  3.09738593,  4.90305008,  7.1623975 , -2.39799528],
       [ 3.33612538,  2.91614779,  5.23909801,  7.82364593, -2.16980398],
       [ 2.85761897,  3.24102863,  4.74057482,  6.8543545 , -2.29660302],
       [ 2.62900699,  2.8290872 ,  4.51041985,  6.36112975, -2.27691735],
       [ 2.97195174,  3.48031659,  4.85203026,  7.10906214, -2.47456036],
       [ 2.85991255,  3.67071548,  4.73092139,  6.82502563, -2.32156406],
       [ 2.44234704,  2.91506437,  4.29428772,  6.0097955 , -2.37032875],
       [ 2.98214032,  2.98669153,  4.87290462,  7.09506438, -2.24243117],
       [ 2.8507065 ,  2.83790819,  4.72738782,  6.83324723, -2.29461692],
       [ 2.6361961 ,  2.8361502 ,  4.51557365,  6.40092168, -2.2109179 ],
       [ 2.85359251,  3.13809951,  4.7095302 ,  6.83851238, -2.44622454],
       [ 2.74791173,  2.96424161,  4.60517019,  6.63147463, -2.54593135],
       [ 2.55489902,  2.78562834,  4.41134269,  6.23871517, -2.36180445],
       [ 2.65955999,  2.82256865,  4.50313746,  6.44983831, -2.74435118],
       [ 2.47569771,  2.85416871,  4.33336146,  6.07672439, -2.09964425],
       [ 2.93438864,  2.99473177,  4.79496376,  7.00488199, -2.41653797],
       [ 2.95282477,  3.28091122,  4.83786795,  7.03702761, -2.28278247],
       [ 2.46300181,  2.64048488,  4.30730309,  6.05748634, -2.54938117],
       [ 2.55645182,  2.57413778,  4.40537688,  6.24591295, -2.66570936],
       [ 2.42125662,  2.99373027,  4.30027413,  5.97660468, -2.52323176],
       [ 2.54317556,  2.62321827,  4.40403271,  6.19868195, -2.33645216],
       [ 2.3896798 ,  2.51365606,  4.23613343,  5.89632935, -2.46298861],
       [ 2.97195174,  2.93916192,  4.86368088,  7.10414409, -2.16282315],
       [ 2.52252351,  2.99021709,  4.38738724,  6.15549483, -2.47088541],
       [ 3.00022218,  3.17220342,  4.90305008,  7.12849595, -2.22562405],
       [ 2.4510051 ,  3.19826487,  4.30716838,  6.03356572, -2.59373985],
       [ 2.54631528,  2.59301339,  4.41024959,  6.22277466, -2.43110052],
       [ 2.52492832,  2.82435066,  4.37185003,  6.17711389, -2.46381074],
       [ 2.49979526,  2.64475535,  4.34704692,  6.13426535, -2.55954399],
       [ 2.52011291,  2.83321334,  4.3643717 ,  6.16814522, -2.5826959 ],
       [ 3.00370044,  2.97858611,  4.87596039,  7.14991684, -2.52323176],
       [ 3.01258939,  3.06851794,  4.91191932,  7.14203657, -2.14558134],
       [ 2.50143595,  2.72195311,  4.35683702,  6.12665082, -2.44495543],
       [ 2.64688377,  2.55567572,  4.50014295,  6.42405832, -2.37418851],
       [ 2.56340971,  2.96269242,  4.43698819,  6.24222327, -2.34559698],
       [ 2.42036813,  2.69327492,  4.26801772,  5.96614674, -2.48819204],
       [ 2.50959926,  2.94549106,  4.35516918,  6.14074625, -2.48734963],
       [ 2.56417983,  2.65535241,  4.43176873,  6.24280675, -2.35788641],
       [ 2.30757263,  2.8639137 ,  4.1652689 ,  5.73914962, -2.29560948],
       [ 2.2623879 ,  2.82375701,  4.12131101,  5.63657372, -2.46734182],
       [ 2.48989419,  2.93916192,  4.33938006,  6.09874821, -2.47860654],
       [ 2.69192082,  2.69056489,  4.55250753,  6.50533553, -2.42193185],
       [ 2.75684037,  2.9559514 ,  4.67376298,  6.63147463, -2.08505728],
       [ 2.62972823,  2.78562834,  4.48322852,  6.38637414, -2.43691681],
       [ 2.80336038,  2.90635446,  4.66908351,  6.73113743, -2.33448864],
       [ 3.0056826 ,  3.28952066,  4.89559848,  7.1180162 , -2.31213051],
       [ 2.50225529,  2.89148225,  4.36067531,  6.12774217, -2.3826028 ],
       [ 2.61666564,  2.77695418,  4.47551698,  6.36147517, -2.48867374],
       [ 2.78315767,  2.77695418,  4.66626529,  6.67013241, -2.31465767],
       [ 2.59972232,  3.33967653,  4.45306741,  6.33167977, -2.58800306],
       [ 2.42214433,  2.56186769,  4.29264882,  5.95661427, -2.089896  ],
       [ 2.40152504,  2.70337261,  4.25802115,  5.92077381, -2.52735497],
       [ 2.48906466,  3.12324559,  4.36627828,  6.1043467 , -2.66858913],
       [ 2.97297529,  3.14458322,  4.85903691,  7.068172  , -2.29263476],
       [ 2.32825284,  2.50307395,  4.18585967,  5.77330854, -2.30298517],
       [ 2.16722346,  2.82375701,  4.01223027,  5.45660235, -2.26432638],
       [ 2.74019465,  2.99423115,  4.62888671,  6.61298145, -2.15416509],
       [ 3.07315617,  3.10368942,  4.97258723,  7.24921506, -2.14814874],
       [ 2.60343015,  2.93863268,  4.47847253,  6.32453816, -2.24526003],
       [ 2.403335  ,  2.69665216,  4.25291404,  5.93542316, -2.55863931],
       [ 2.51284602,  2.7047113 ,  4.36041988,  6.15081597, -2.44391827],
       [ 2.3924258 ,  2.9226238 ,  4.25405121,  5.91350301, -2.29859307],
       [ 2.55334381,  3.06198807,  4.41437281,  6.24319556, -2.58349018],
       [ 2.88981605,  3.02819946,  4.76898827,  6.89942064, -2.26721795],
       [ 2.47569771,  3.05258509,  4.3358518 ,  6.0725836 , -2.3255467 ],
       [ 2.74084002,  3.04832472,  4.63375764,  6.68847924, -2.18925641],
       [ 2.41233596,  3.0638581 ,  4.2619754 ,  5.94096041, -2.28474517],
       [ 2.44841554,  2.94654203,  4.30676415,  6.01542518, -2.45970685],
       [ 2.4518668 ,  2.77383794,  4.32360271,  6.01175725, -2.21824394],
       [ 2.37954613,  3.09013295,  4.23105839,  5.88582622, -2.43030483],
       [ 2.70136121,  3.11484775,  4.62595273,  6.52941884, -2.30789919],
       [ 3.00469201,  2.97246365,  4.89634615,  7.13089883, -2.17771611],
       [ 2.39516427,  2.84490938,  4.27290907,  5.91754886, -2.41743493],
       [ 2.48407297,  3.21446612,  4.35169628,  6.08972492, -2.27302629],
       [ 2.87638552,  3.33327537,  4.76473476,  6.88918389, -2.30288514],
       [ 2.69462718,  2.8713022 ,  4.56309741,  6.51441635, -2.38825192],
       [ 2.97501923,  3.21887582,  4.84968376,  7.08254857, -2.27108643],
       [ 2.59376105,  3.42491391,  4.45829299,  6.32292424, -2.38108732],
       [ 2.83790819,  3.30137705,  4.71133038,  6.83615186, -2.31283747],
       [ 2.4510051 ,  2.91017439,  4.30244216,  6.02272094, -2.46416329],
       [ 2.57794152,  2.90251989,  4.43414459,  6.2865566 , -2.59481081],
       [ 2.57566101,  3.0320642 ,  4.45411471,  6.28581186, -2.44472486],
       [ 2.8678989 ,  3.14974009,  4.77912349,  6.88806265, -2.37633928],
       [ 2.48823444,  3.33719205,  4.34185547,  6.10902534, -2.43588794],
       [ 2.44147709,  2.68033636,  4.30392995,  6.00364012, -2.25761173],
       [ 2.78809291,  2.97092715,  4.69866053,  6.70416923, -2.27691735],
       [ 2.75556972,  2.42303125,  4.63278535,  6.61633289, -2.26048392],
       [ 2.52172062,  2.79789091,  4.41703174,  6.16688736, -2.35240579],
       [ 2.81480974,  3.0056826 ,  4.67376298,  6.75413779, -2.59066725],
       [ 2.50552594,  3.11084508,  4.35901386,  6.14525802, -2.50201212],
       [ 2.52252351,  2.55178618,  4.36729364,  6.16814522, -2.60748115],
       [ 2.57718193,  3.0223742 ,  4.43153083,  6.28915883, -2.61251277],
       [ 2.52332576,  2.85128437,  4.38763587,  6.17399442, -2.41597778],
       [ 3.02480552,  3.0558862 ,  4.92580336,  7.18538702, -2.22100511],
       [ 2.62611682,  3.19826487,  4.52536912,  6.39007287, -2.15244243],
       [ 3.13939962,  2.98719594,  5.0245382 ,  7.42773884, -2.37064982],
       [ 2.73825604,  3.17596832,  4.64246597,  6.59482377, -2.13453151],
       [ 2.46300181,  2.68716699,  4.33480399,  6.05443935, -2.51342959],
       [ 2.69530263,  2.68784749,  4.55029152,  6.52312168, -2.46840358],
       [ 2.59525471,  3.02140002,  4.48458322,  6.3220265 , -2.20183519],
       [ 2.90744736,  3.02431973,  4.79413629,  6.95844839, -2.23679735],
       [ 2.28716684,  2.75238601,  4.14313473,  5.68085497, -2.35472085],
       [ 2.59972232,  2.93119375,  4.47095284,  6.31191628, -2.23026443],
       [ 2.63476241,  2.57794152,  4.5032482 ,  6.38721596, -2.08104282],
       [ 2.46385324,  2.86562359,  4.32928492,  6.04713574, -2.23212663],
       [ 2.39425228,  2.86903462,  4.25971775,  5.90153984, -2.33438541],
       [ 3.02286094,  3.03783345,  4.92580336,  7.17625453, -2.25761173],
       [ 2.45873378,  3.19622113,  4.33558995,  6.0073379 , -2.09070473],
       [ 2.44581926,  2.67000213,  4.31281052,  5.99868839, -2.30418637],
       [ 2.69056489,  3.23553627,  4.550714  ,  6.50518597, -2.49193126],
       [ 2.58097412,  3.33434507,  4.44123849,  6.28860178, -2.44518606],
       [ 2.32825284,  2.80819715,  4.18737943,  5.77081788, -2.42170652],
       [ 2.27037177,  2.96217549,  4.1116932 ,  5.65494231, -2.46616341],
       [ 2.38139627,  3.18676577,  4.23251103,  5.89053863, -2.50201212],
       [ 2.38508631,  3.06712227,  4.22697972,  5.88749196, -2.59950975],
       [ 2.6426224 ,  3.30137705,  4.51502664,  6.3975961 , -2.30971042],
       [ 3.07083975,  3.10861443,  4.95582706,  7.29912146, -2.19822508],
       [ 3.02529108,  3.37861088,  4.94235645,  7.1428274 , -2.13876701]])

# **Using complex functions via lamba**

In [13]:
transformer = FunctionTransformer(
    lambda x: x * 2,
    validate=True
)

In [14]:
transformer.fit_transform(df)

array([[3.9380e+01, 4.2500e+01, 2.6000e+02, 2.4060e+03, 2.1920e-01],
       [2.2840e+01, 4.0760e+01, 1.5516e+02, 7.7220e+02, 2.8500e-01],
       [2.6000e+01, 4.3640e+01, 1.7500e+02, 1.0396e+03, 2.5460e-01],
       [3.1700e+01, 4.7900e+01, 2.0740e+02, 1.5654e+03, 1.6802e-01],
       [2.7460e+01, 4.5220e+01, 1.8720e+02, 1.1566e+03, 2.2620e-01],
       [3.9620e+01, 4.4300e+01, 2.6000e+02, 2.5200e+03, 1.9662e-01],
       [2.6160e+01, 3.1420e+01, 1.7126e+02, 1.0400e+03, 2.1500e-01],
       [1.9008e+01, 2.4880e+01, 1.2068e+02, 5.4780e+02, 2.0480e-01],
       [3.4280e+01, 3.2800e+01, 2.3200e+02, 1.8254e+03, 2.3720e-01],
       [2.9160e+01, 4.3060e+01, 1.9482e+02, 1.2896e+03, 2.1080e-01],
       [3.4040e+01, 4.7960e+01, 2.2560e+02, 1.7986e+03, 2.3940e-01],
       [3.8540e+01, 5.2940e+01, 2.5580e+02, 2.3240e+03, 1.8802e-01],
       [2.6060e+01, 3.6840e+01, 1.6522e+02, 1.0476e+03, 1.7966e-01],
       [2.6960e+01, 4.1640e+01, 1.7680e+02, 1.1184e+03, 2.0320e-01],
       [3.8140e+01, 4.9620e+01, 2.5660e+02, 2.2080e+03, 1.8162e-01],
       [2.6560e+01, 4.0560e+01, 1.7464e+02, 1.0904e+03, 2.0820e-01],
       [3.7300e+01, 3.5200e+01, 2.4740e+02, 2.1520e+03, 2.1980e-01],
       [2.3880e+01, 3.6480e+01, 1.5142e+02, 8.7520e+02, 1.6522e-01],
       [3.6440e+01, 3.7400e+01, 2.4060e+02, 2.0660e+03, 2.2960e-01],
       [2.6100e+01, 3.8620e+01, 1.6522e+02, 1.0544e+03, 1.6120e-01],
       [1.7236e+01, 2.3580e+01, 1.0868e+02, 4.4900e+02, 1.9504e-01],
       [1.8346e+01, 2.7720e+01, 1.1840e+02, 5.2180e+02, 1.5442e-01],
       [2.5360e+01, 4.7680e+01, 1.6538e+02, 9.9800e+02, 2.2440e-01],
       [1.8058e+01, 3.4660e+01, 1.1758e+02, 5.0100e+02, 2.1320e-01],
       [1.7776e+01, 2.9280e+01, 1.1758e+02, 4.8800e+02, 1.9566e-01],
       [2.7600e+01, 3.1580e+01, 1.8086e+02, 1.1682e+03, 2.0140e-01],
       [2.7060e+01, 2.1880e+01, 1.7582e+02, 1.1184e+03, 2.5820e-01],
       [4.0360e+01, 4.7940e+01, 2.8740e+02, 2.4900e+03, 2.5720e-01],
       [1.9752e+01, 3.8800e+01, 1.2790e+02, 5.9660e+02, 2.0100e-01],
       [2.6220e+01, 3.1120e+01, 1.7442e+02, 1.0604e+03, 2.7960e-01],
       [2.8520e+01, 3.9300e+01, 1.9566e+02, 1.2598e+03, 1.5674e-01],
       [2.1020e+01, 4.0380e+01, 1.3728e+02, 6.6840e+02, 2.2440e-01],
       [3.7320e+01, 3.4240e+01, 2.4280e+02, 2.1540e+03, 2.1080e-01],
       [3.8000e+01, 3.7820e+01, 2.4680e+02, 2.2760e+03, 1.6434e-01],
       [3.0200e+01, 3.2780e+01, 1.9916e+02, 1.3490e+03, 2.3000e-01],
       [3.9580e+01, 5.0240e+01, 2.6080e+02, 2.3840e+03, 2.0300e-01],
       [3.6900e+01, 4.3820e+01, 2.4040e+02, 2.1500e+03, 1.8860e-01],
       [2.5540e+01, 4.4940e+01, 1.6344e+02, 1.0126e+03, 1.8110e-01],
       [2.2560e+01, 2.6780e+01, 1.4600e+02, 7.6960e+02, 2.3280e-01],
       [2.2860e+01, 3.4620e+01, 1.4732e+02, 7.9600e+02, 2.1840e-01],
       [2.3600e+01, 3.3160e+01, 1.5798e+02, 8.6400e+02, 2.1820e-01],
       [2.6000e+01, 4.1560e+01, 1.6702e+02, 1.0388e+03, 2.2700e-01],
       [1.6438e+01, 4.1400e+01, 1.0654e+02, 4.0780e+02, 1.8810e-01],
       [2.4120e+01, 2.5480e+01, 1.5368e+02, 8.9720e+02, 1.8622e-01],
       [3.8380e+01, 3.1880e+01, 2.5260e+02, 2.3140e+03, 1.7388e-01],
       [4.6540e+01, 4.4080e+01, 3.0420e+02, 3.3720e+03, 1.6878e-01],
       [2.1600e+01, 1.9420e+01, 1.3754e+02, 7.1520e+02, 1.9188e-01],
       [3.4940e+01, 4.9360e+01, 2.3220e+02, 1.9692e+03, 2.0980e-01],
       [2.9940e+01, 3.3900e+01, 1.9244e+02, 1.3718e+03, 1.9710e-01],
       [2.4640e+01, 2.4780e+01, 1.5770e+02, 9.2820e+02, 2.0560e-01],
       [3.2920e+01, 4.0220e+01, 2.1860e+02, 1.6658e+03, 1.9662e-01],
       [2.2820e+01, 2.9840e+01, 1.4706e+02, 8.0400e+02, 1.8118e-01],
       [2.0160e+01, 3.0220e+01, 1.2752e+02, 6.3500e+02, 1.8534e-01],
       [2.3620e+01, 3.4780e+01, 1.5054e+02, 8.5780e+02, 2.0140e-01],
       [3.8360e+01, 4.4980e+01, 2.5500e+02, 2.2960e+03, 1.7046e-01],
       [2.8900e+01, 4.0440e+01, 1.8898e+02, 1.2854e+03, 1.9744e-01],
       [3.0240e+01, 3.3360e+01, 1.9756e+02, 1.4332e+03, 1.7752e-01],
       [2.6220e+01, 4.5080e+01, 1.7404e+02, 1.0588e+03, 2.0040e-01],
       [4.1160e+01, 4.4280e+01, 2.6940e+02, 2.5800e+03, 1.8180e-01],
       [5.6220e+01, 3.6940e+01, 3.7700e+02, 4.9980e+03, 2.2840e-01],
       [3.4840e+01, 5.1120e+01, 2.2900e+02, 1.8960e+03, 2.0120e-01],
       [2.7720e+01, 3.3860e+01, 1.8192e+02, 1.1578e+03, 2.0520e-01],
       [3.9060e+01, 6.4940e+01, 2.5600e+02, 2.4460e+03, 1.6840e-01],
       [3.4920e+01, 7.8560e+01, 2.2680e+02, 1.8412e+03, 1.9624e-01],
       [2.3000e+01, 3.6900e+01, 1.4656e+02, 8.1480e+02, 1.8690e-01],
       [3.9460e+01, 3.9640e+01, 2.6140e+02, 2.4120e+03, 2.1240e-01],
       [3.4600e+01, 3.4160e+01, 2.2600e+02, 1.8564e+03, 2.0160e-01],
       [2.7920e+01, 3.4100e+01, 1.8286e+02, 1.2048e+03, 2.1920e-01],
       [3.4700e+01, 4.6120e+01, 2.2200e+02, 1.8662e+03, 1.7324e-01],
       [3.1220e+01, 3.8760e+01, 2.0000e+02, 1.5172e+03, 1.5680e-01],
       [2.5740e+01, 3.2420e+01, 1.6476e+02, 1.0244e+03, 1.8850e-01],
       [2.8580e+01, 3.3640e+01, 1.8060e+02, 1.2652e+03, 1.2858e-01],
       [2.3780e+01, 3.4720e+01, 1.5240e+02, 8.7120e+02, 2.4500e-01],
       [3.7620e+01, 3.9960e+01, 2.4180e+02, 2.2040e+03, 1.7846e-01],
       [3.8320e+01, 5.3200e+01, 2.5240e+02, 2.2760e+03, 2.0400e-01],
       [2.3480e+01, 2.8040e+01, 1.4848e+02, 8.5460e+02, 1.5626e-01],
       [2.5780e+01, 2.6240e+01, 1.6378e+02, 1.0318e+03, 1.3910e-01],
       [2.2520e+01, 3.9920e+01, 1.4744e+02, 7.8820e+02, 1.6040e-01],
       [2.5440e+01, 2.7560e+01, 1.6356e+02, 9.8420e+02, 1.9334e-01],
       [2.1820e+01, 2.4700e+01, 1.3828e+02, 7.2740e+02, 1.7036e-01],
       [3.9060e+01, 3.7800e+01, 2.5900e+02, 2.4340e+03, 2.3000e-01],
       [2.4920e+01, 3.9780e+01, 1.6086e+02, 9.4260e+02, 1.6902e-01],
       [4.0180e+01, 4.7720e+01, 2.6940e+02, 2.4940e+03, 2.1600e-01],
       [2.3200e+01, 4.8980e+01, 1.4846e+02, 8.3440e+02, 1.4948e-01],
       [2.5520e+01, 2.6740e+01, 1.6458e+02, 1.0082e+03, 1.7588e-01],
       [2.4980e+01, 3.3700e+01, 1.5838e+02, 9.6320e+02, 1.7022e-01],
       [2.4360e+01, 2.8160e+01, 1.5450e+02, 9.2280e+02, 1.5468e-01],
       [2.4860e+01, 3.4000e+01, 1.5720e+02, 9.5460e+02, 1.5114e-01],
       [4.0320e+01, 3.9320e+01, 2.6220e+02, 2.5480e+03, 1.6040e-01],
       [4.0680e+01, 4.3020e+01, 2.7180e+02, 2.5280e+03, 2.3400e-01],
       [2.4400e+01, 3.0420e+01, 1.5602e+02, 9.1580e+02, 1.7346e-01],
       [2.8220e+01, 2.5760e+01, 1.8006e+02, 1.2330e+03, 1.8618e-01],
       [2.5960e+01, 3.8700e+01, 1.6904e+02, 1.0280e+03, 1.9158e-01],
       [2.2500e+01, 2.9560e+01, 1.4276e+02, 7.8000e+02, 1.6612e-01],
       [2.4600e+01, 3.8040e+01, 1.5576e+02, 9.2880e+02, 1.6626e-01],
       [2.5980e+01, 2.8460e+01, 1.6816e+02, 1.0286e+03, 1.8924e-01],
       [2.0100e+01, 3.5060e+01, 1.2882e+02, 6.2160e+02, 2.0140e-01],
       [1.9212e+01, 3.3680e+01, 1.2328e+02, 5.6100e+02, 1.6962e-01],
       [2.4120e+01, 3.7800e+01, 1.5332e+02, 8.9060e+02, 1.6772e-01],
       [2.9520e+01, 2.9480e+01, 1.8974e+02, 1.3374e+03, 1.7750e-01],
       [3.1500e+01, 3.8440e+01, 2.1420e+02, 1.5172e+03, 2.4860e-01],
       [2.7740e+01, 3.2420e+01, 1.7704e+02, 1.1874e+03, 1.7486e-01],
       [3.3000e+01, 3.6580e+01, 2.1320e+02, 1.6762e+03, 1.9372e-01],
       [4.0400e+01, 5.3660e+01, 2.6740e+02, 2.4680e+03, 1.9810e-01],
       [2.4420e+01, 3.6040e+01, 1.5662e+02, 9.1680e+02, 1.8462e-01],
       [2.7380e+01, 3.2140e+01, 1.7568e+02, 1.1582e+03, 1.6604e-01],
       [3.2340e+01, 3.2140e+01, 2.1260e+02, 1.5770e+03, 1.9760e-01],
       [2.6920e+01, 5.6420e+01, 1.7178e+02, 1.1242e+03, 1.5034e-01],
       [2.2540e+01, 2.5920e+01, 1.4632e+02, 7.7260e+02, 2.4740e-01],
       [2.2080e+01, 2.9860e+01, 1.4134e+02, 7.4540e+02, 1.5974e-01],
       [2.4100e+01, 4.5440e+01, 1.5750e+02, 8.9560e+02, 1.3870e-01],
       [3.9100e+01, 4.6420e+01, 2.5780e+02, 2.3480e+03, 2.0200e-01],
       [2.0520e+01, 2.4440e+01, 1.3150e+02, 6.4320e+02, 1.9992e-01],
       [1.7468e+01, 3.3680e+01, 1.1054e+02, 4.6860e+02, 2.0780e-01],
       [3.0980e+01, 3.9940e+01, 2.0480e+02, 1.4894e+03, 2.3200e-01],
       [4.3220e+01, 4.4560e+01, 2.8880e+02, 2.8140e+03, 2.3340e-01],
       [2.7020e+01, 3.7780e+01, 1.7620e+02, 1.1162e+03, 2.1180e-01],
       [2.2120e+01, 2.9660e+01, 1.4062e+02, 7.5640e+02, 1.5482e-01],
       [2.4680e+01, 2.9900e+01, 1.5658e+02, 9.3820e+02, 1.7364e-01],
       [2.1880e+01, 3.7180e+01, 1.4078e+02, 7.4000e+02, 2.0080e-01],
       [2.5700e+01, 4.2740e+01, 1.6526e+02, 1.0290e+03, 1.5102e-01],
       [3.5980e+01, 4.1320e+01, 2.3560e+02, 1.9834e+03, 2.0720e-01],
       [2.3780e+01, 4.2340e+01, 1.5278e+02, 8.6760e+02, 1.9546e-01],
       [3.1000e+01, 4.2160e+01, 2.0580e+02, 1.6062e+03, 2.2400e-01],
       [2.2320e+01, 4.2820e+01, 1.4190e+02, 7.6060e+02, 2.0360e-01],
       [2.3140e+01, 3.8080e+01, 1.4840e+02, 8.1940e+02, 1.7092e-01],
       [2.3220e+01, 3.2040e+01, 1.5092e+02, 8.1640e+02, 2.1760e-01],
       [2.1600e+01, 4.3960e+01, 1.3758e+02, 7.1980e+02, 1.7602e-01],
       [2.9800e+01, 4.5060e+01, 2.0420e+02, 1.3700e+03, 1.9894e-01],
       [4.0360e+01, 3.9080e+01, 2.6760e+02, 2.5000e+03, 2.2660e-01],
       [2.1940e+01, 3.4400e+01, 1.4346e+02, 7.4300e+02, 1.7830e-01],
       [2.3980e+01, 4.9780e+01, 1.5522e+02, 8.8260e+02, 2.0600e-01],
       [3.5500e+01, 5.6060e+01, 2.3460e+02, 1.9632e+03, 1.9994e-01],
       [2.9600e+01, 3.5320e+01, 1.9176e+02, 1.3496e+03, 1.8358e-01],
       [3.9180e+01, 5.0000e+01, 2.5540e+02, 2.3820e+03, 2.0640e-01],
       [2.6760e+01, 6.1440e+01, 1.7268e+02, 1.1144e+03, 1.8490e-01],
       [3.4160e+01, 5.4300e+01, 2.2240e+02, 1.8618e+03, 1.9796e-01],
       [2.3200e+01, 3.6720e+01, 1.4776e+02, 8.2540e+02, 1.7016e-01],
       [2.6340e+01, 3.6440e+01, 1.6856e+02, 1.0746e+03, 1.4932e-01],
       [2.6280e+01, 4.1480e+01, 1.7196e+02, 1.0738e+03, 1.7350e-01],
       [3.5200e+01, 4.6660e+01, 2.3800e+02, 1.9610e+03, 1.8578e-01],
       [2.4080e+01, 5.6280e+01, 1.5370e+02, 8.9980e+02, 1.7504e-01],
       [2.2980e+01, 2.9180e+01, 1.4798e+02, 8.0980e+02, 2.0920e-01],
       [3.2500e+01, 3.9020e+01, 2.1960e+02, 1.6316e+03, 2.0520e-01],
       [3.1460e+01, 2.2560e+01, 2.0560e+02, 1.4944e+03, 2.0860e-01],
       [2.4900e+01, 3.2820e+01, 1.6570e+02, 9.5340e+02, 1.9028e-01],
       [3.3380e+01, 4.0400e+01, 2.1420e+02, 1.7152e+03, 1.4994e-01],
       [2.4500e+01, 4.4880e+01, 1.5636e+02, 9.3300e+02, 1.6384e-01],
       [2.4920e+01, 2.5660e+01, 1.5766e+02, 9.5460e+02, 1.4744e-01],
       [2.6320e+01, 4.1080e+01, 1.6812e+02, 1.0774e+03, 1.4670e-01],
       [2.4940e+01, 3.4620e+01, 1.6090e+02, 9.6020e+02, 1.7856e-01],
       [4.1180e+01, 4.2480e+01, 2.7560e+02, 2.6400e+03, 2.1700e-01],
       [2.7640e+01, 4.8980e+01, 1.8466e+02, 1.1918e+03, 2.3240e-01],
       [4.6180e+01, 3.9660e+01, 3.0420e+02, 3.3640e+03, 1.8684e-01],
       [3.0920e+01, 4.7900e+01, 2.0760e+02, 1.4626e+03, 2.3660e-01],
       [2.3480e+01, 2.9380e+01, 1.5262e+02, 8.5200e+02, 1.6198e-01],
       [2.9620e+01, 2.9400e+01, 1.8932e+02, 1.3614e+03, 1.6944e-01],
       [2.6800e+01, 4.1040e+01, 1.7728e+02, 1.1134e+03, 2.2120e-01],
       [3.6620e+01, 4.1160e+01, 2.4160e+02, 2.1040e+03, 2.1360e-01],
       [1.9694e+01, 3.1360e+01, 1.2600e+02, 5.8640e+02, 1.8984e-01],
       [2.6920e+01, 3.7500e+01, 1.7488e+02, 1.1022e+03, 2.1500e-01],
       [2.7880e+01, 2.6340e+01, 1.8062e+02, 1.1884e+03, 2.4960e-01],
       [2.3500e+01, 3.5120e+01, 1.5178e+02, 8.4580e+02, 2.1460e-01],
       [2.1920e+01, 3.5240e+01, 1.4158e+02, 7.3120e+02, 1.9374e-01],
       [4.1100e+01, 4.1720e+01, 2.7560e+02, 2.6160e+03, 2.0920e-01],
       [2.3380e+01, 4.8880e+01, 1.5274e+02, 8.1280e+02, 2.4720e-01],
       [2.3080e+01, 2.8880e+01, 1.4930e+02, 8.0580e+02, 1.9968e-01],
       [2.9480e+01, 5.0840e+01, 1.8940e+02, 1.3372e+03, 1.6550e-01],
       [2.6420e+01, 5.6120e+01, 1.6976e+02, 1.0768e+03, 1.7342e-01],
       [2.0520e+01, 3.3160e+01, 1.3170e+02, 6.4160e+02, 1.7754e-01],
       [1.9366e+01, 3.8680e+01, 1.2210e+02, 5.7140e+02, 1.6982e-01],
       [2.1640e+01, 4.8420e+01, 1.3778e+02, 7.2320e+02, 1.6384e-01],
       [2.1720e+01, 4.2960e+01, 1.3702e+02, 7.2100e+02, 1.4862e-01],
       [2.8100e+01, 5.4300e+01, 1.8276e+02, 1.2008e+03, 1.9858e-01],
       [4.3120e+01, 4.4780e+01, 2.8400e+02, 2.9580e+03, 2.2200e-01],
       [4.1200e+01, 5.8660e+01, 2.8020e+02, 2.5300e+03, 2.3560e-01]])

# **Passing a second argument via kw_args**

In [15]:
transformer = FunctionTransformer(
    lambda x, a: x*a,
    kw_args={"a": 3}
)

In [16]:
transformer.fit_transform(df)

     mean radius  mean texture  mean perimeter  mean area  mean smoothness
2          59.07         63.75          390.00     3609.0          0.32880
3          34.26         61.14          232.74     1158.3          0.42750
8          39.00         65.46          262.50     1559.4          0.38190
13         47.55         71.85          311.10     2348.1          0.25203
14         41.19         67.83          280.80     1734.9          0.33930
..           ...           ...             ...        ...              ...
549        32.46         72.63          206.67     1084.8          0.24576
550        32.58         64.44          205.53     1081.5          0.22293
560        42.15         81.45          274.14     1801.2          0.29787
564        64.68         67.17          426.00     4437.0          0.33300
567        61.80         87.99          420.30     3795.0          0.35340

[176 rows x 5 columns]

### ***Note:*** **we can also define an external function and pass it as an arg.**