# Exercise 1

* Load **sample_dataset.csv**
* Consider only the first 3 columns and remove all the records that have missings
* Calculate the mean value of "mean radius"
* Use a ColumnTransformer to apply the following transformations:
    * Binarize "mean radius" using a threshold equal to the mean value
    * Binning of "mean texture" with 10 uniform bins and one-hot encoded dense output
    * Binning of "mean perimeter" with 5 quantile bins and ordinal encoding output

In [1]:
import pandas as pd
from get_path import get_path as gp
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Binarizer, KBinsDiscretizer

In [2]:
df = pd.read_csv(gp()).iloc[:, :3].dropna()

In [13]:
df.head()

   mean radius  mean texture  mean perimeter
1        20.57         17.77          132.90
2        19.69         21.25          130.00
3        11.42         20.38           77.58
5        12.45         15.70           82.57
7        13.71         20.83           90.20

In [14]:
(m := float(df["mean radius"].mean()))

14.107932467532468

In [15]:
transformer = ColumnTransformer([
    ("mean_radius", Binarizer(threshold = m), [0]),
    ("mean_texture", KBinsDiscretizer(n_bins = 10, strategy = "uniform", encode = "onehot-dense"), [1]),
    ("mean_perimeter", KBinsDiscretizer(n_bins = 5, strategy = "quantile", encode = "ordinal", quantile_method='averaged_inverted_cdf'), [2])
])

In [16]:
transformer.fit_transform(df)

array([[1., 0., 0., ..., 0., 0., 4.],
       [1., 0., 0., ..., 0., 0., 4.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 4.],
       [1., 0., 0., ..., 0., 0., 3.],
       [1., 0., 0., ..., 0., 0., 4.]], shape=(385, 12))

# Exercise 2

* Load **sample_dataset.csv**
* Consider only the first 3 columns and remove all the records that have missings
* Use a ColumnTransformer to apply the following transformations:
    * Yeo-Johnson power transform of "mean radius"
    * Box-Cox transformation of "mean texture"
    * Calculate the logarithm of "mean perimeter"

In [20]:
import pandas as pd
from get_path import get_path as gp
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer, FunctionTransformer
import numpy as np

In [21]:
df = pd.read_csv(gp()).iloc[:, :3].dropna()

In [22]:
df.head()

   mean radius  mean texture  mean perimeter
1        20.57         17.77          132.90
2        19.69         21.25          130.00
3        11.42         20.38           77.58
5        12.45         15.70           82.57
7        13.71         20.83           90.20

In [25]:
transformer = ColumnTransformer([
    ("mean_radius_transformer", PowerTransformer(method = "yeo-johnson"), ["mean radius"]),
    ("mean_texture_transformer", PowerTransformer(method = "box-cox"), ["mean texture"]),
    ("mean_perimeter_transformer", FunctionTransformer(np.log), ["mean perimeter"])
])

In [26]:
transformer.fit_transform(df)

array([[ 1.63387526, -0.25875217,  4.88959697],
       [ 1.48019618,  0.54975194,  4.86753445],
       [-0.76778428,  0.36164666,  4.35130966],
       ...,
       [ 1.79501354,  0.78415652,  4.95582706],
       [ 0.84387905,  1.79038802,  4.68490515],
       [ 1.63893429,  1.98216691,  4.94235645]], shape=(385, 3))