In [22]:
import pandas as pd
from get_path import get_path as gp
from sklearn.compose import ColumnTransformer,  make_column_selector
from sklearn.impute import SimpleImputer, KNNImputer

In [23]:
df = pd.read_csv(gp())

In [24]:
df.head(3)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.8,1001.0,0.1184,0.2776,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.9,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.0,1203.0,0.1096,0.1599,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0

# **Exercise 1**
- Load **sample_dataset.csv**
- Replace missing categorical values with 'N'
- Replace missing numerical values with mean value

In [25]:
cleaner = ColumnTransformer([
    ("categorical_transformer", SimpleImputer(strategy="constant", fill_value="N"), make_column_selector(dtype_include="object")),
    ("numerical_transformer", SimpleImputer(strategy="mean"), make_column_selector(dtype_exclude="object"))
])

In [26]:
cleaned = cleaner.fit_transform(df)
cleaned

array([['A', 14.059547717842323, 10.38, ..., 0.4601, 0.1189, 0.0],
       ['A', 20.57, 17.77, ..., 0.275, 0.08436317021276594, 0.0],
       ['A', 19.69, 21.25, ..., 0.3613, 0.08758, 0.0],
       ...,
       ['A', 16.6, 28.08, ..., 0.2218, 0.0782, 0.0],
       ['A', 20.6, 29.33, ..., 0.4087, 0.124, 0.0],
       ['A', 7.76, 19.311829268292684, ..., 0.2871, 0.07039, 1.0]],
      shape=(569, 31), dtype=object)

In [27]:
cleaned[0]

array(['A', 14.059547717842323, 10.38, 122.8, 1001.0, 0.1184, 0.2776,
       0.3001, 0.1471, 0.2419, 0.07871, 1.095, 1.2096921658986175, 8.589,
       0.006399, 0.025096302631578946, 0.03124424538258575, 0.01587,
       0.03003, 0.006193, 25.38, 17.33, 107.32284782608694, 2019.0,
       0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189, 0.0], dtype=object)

In [28]:
cleaned = pd.DataFrame(
    cleaned,
    columns=cleaner.get_feature_names_out(),
    index=df.index
)

In [29]:
cleaned

,categorical_transformer__area error,numerical_transformer__mean radius,numerical_transformer__mean texture,numerical_transformer__mean perimeter,numerical_transformer__mean area,numerical_transformer__mean smoothness,numerical_transformer__mean compactness,numerical_transformer__mean concavity,numerical_transformer__mean concave points,numerical_transformer__mean symmetry,...,numerical_transformer__worst texture,numerical_transformer__worst perimeter,numerical_transformer__worst area,numerical_transformer__worst smoothness,numerical_transformer__worst compactness,numerical_transformer__worst concavity,numerical_transformer__worst concave points,numerical_transformer__worst symmetry,numerical_transformer__worst fractal dimension,numerical_transformer__target
0,A,14.059548,10.38,122.8,1001.0,0.1184,0.2776,0.3001,0.1471,0.2419,...,17.33,107.322848,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189,0.0
1,A,20.57,17.77,132.9,1326.0,0.097156,0.104531,0.0869,0.07017,0.181405,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.186,0.275,0.084363,0.0
2,A,19.69,21.25,130.0,1203.0,0.1096,0.1599,0.094063,0.049115,0.181405,...,25.53,107.322848,1709.0,0.1444,0.4245,0.4504,0.243,0.3613,0.08758,0.0
3,A,11.42,20.38,77.58,386.1,0.1425,0.2839,0.2414,0.049115,0.2597,...,26.5,107.322848,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.173,0.0
4,N,20.29,14.34,92.039025,661.522581,0.097156,0.1328,0.198,0.049115,0.1809,...,16.67,152.2,1575.0,0.1374,0.256748,0.4,0.1625,0.2364,0.07678,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,A,21.56,22.39,142.0,1479.0,0.111,0.104531,0.2439,0.1389,0.1726,...,26.4,166.1,2027.0,0.141,0.2113,0.4107,0.2216,0.206,0.07115,0.0
565,A,14.059548,28.25,131.2,1261.0,0.0978,0.1034,0.144,0.09791,0.1752,...,38.25,155.0,1731.0,0.1166,0.1922,0.3215,0.1628,0.2572,0.084363,0.0
566,A,16.6,28.08,108.3,661.522581,0.08455,0.1023,0.094063,0.05302,0.159,...,34.12,126.7,1124.0,0.1139,0.256748,0.3403,0.1418,0.2218,0.0782,0.0
567,A,20.6,29.33,140.1,1265.0,0.1178,0.277,0.3514,0.152,0.2397,...,25.599058,184.6,1821.0,0.165,0.8681,0.9387,0.265,0.4087,0.124,0.0
568,A,7.76,19.311829,47.92,181.0,0.05263,0.04362,0.0,0.0,0.1587,...,30.37,59.16,893.873828,0.08996,0.256748,0.0,0.0,0.2871,0.07039,1.0

In [30]:
cleaned["categorical_transformer__area error"].value_counts()

categorical_transformer__area error
A    489
N     75
B      4
C      1
Name: count, dtype: int64

# **Exercise 2**
- Load **`sample_datatset.csv`**
- Replace the missings in float variables with 10 neighbours and a distance-style weight
- Replace the missings in categorical variables with the most frequent value

In [31]:
df = pd.read_csv(gp())

In [32]:
cleaner = ColumnTransformer([
    ("float", KNNImputer(n_neighbors=10, weights="distance"), make_column_selector(dtype_include="float64")),
    ("category", SimpleImputer(strategy="most_frequent"), make_column_selector(dtype_include=["object", "category"]))
])

In [36]:
cleaner.fit_transform(df)

array([[15.637884267617215, 10.38, 122.8, ..., 0.4601, 0.1189, 'A'],
       [20.57, 17.77, 132.9, ..., 0.275, 0.08216467870588635, 'A'],
       [19.69, 21.25, 130.0, ..., 0.3613, 0.08758, 'A'],
       ...,
       [16.6, 28.08, 108.3, ..., 0.2218, 0.0782, 'A'],
       [20.6, 29.33, 140.1, ..., 0.4087, 0.124, 'A'],
       [7.76, 21.692427354276592, 47.92, ..., 0.2871, 0.07039, 'A']],
      shape=(569, 30), dtype=object)